Repository sprint15-part4-team5/wazy, pull requests merged in 2025-07, with the labels that each got.

#12 ✨Feat: PhotoSection 컴포넌트 구현
  src/app/activities/[id]/page.tsx
  src/components/activities/PhotoSection.tsx
Labels: 🎨style, ✨feat

#15 ✨feat: 랜딩페이지 카드 아이템 구현
  src/app/globals.css
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/app/profile/reservations/page.tsx
  src/components/landing/LandingCard.tsx
Labels: 🎨style, ✨feat

#13 Feat/experience add edit UI
  public/icons/icon_blue_plus.svg
  public/icons/icon_white_delete.svg
  src/app/globals.css
  src/app/profile/myExperiences/add/page.tsx
  src/components/common/Input.tsx
  src/components/myExperiencesAdd/AddressInput.tsx
  src/components/myExperiencesAdd/BannerImageInput.tsx
  src/components/myExperiencesAdd/CategoryInput.tsx
  src/components/myExperiencesAdd/DescriptionInput.tsx
  src/components/myExperiencesAdd/IntroImagesInput.tsx
  src/components/myExperiencesAdd/PriceInput.tsx
  src/components/myExperiencesAdd/ReserveTimesInput.tsx
  src/components/myExperiencesAdd/TitleInput.tsx
Labels: 📝docs, ✨feat

#19 5 profile layout 구현(추후 스타일링 수정예정), myExperiences 초기 구
  public/imgs/thumbnail.jpg
  src/app/profile/info/page.tsx
  src/app/profile/layout.tsx
  src/app/profile/myExperiences/page.tsx
  src/app/profile/page.tsx
  src/app/profile/reservationStatus/page.tsx
  src/components/profile/ExperienceCard.tsx
  src/components/profile/ProfileMenu.tsx
Labels: ✨feat

#25 feat/반응형구현-체험 추가 및 수정 페이지
  public/icons/icon_gray_minus.svg
  src/app/experiences/add/page.tsx
  src/app/experiences/edit/page.tsx
  src/components/common/Input.tsx
  src/components/myExperiencesAddEdit/BannerImageInput.tsx
  src/components/myExperiencesAddEdit/DescriptionInput.tsx
  src/components/myExperiencesAddEdit/IntroImagesInput.tsx
  src/components/myExperiencesAddEdit/ReserveTimesInput.tsx
Labels: 🎨style

#32 ✨Feat: Dropdown 컴포넌트 구현
  src/app/activities/[id]/page.tsx
  src/components/activities/ActivitesDropdown.tsx
  src/components/common/Dropdown/Content.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/Item.tsx
  src/components/common/Dropdown/Trigger.tsx
Labels: 🎨style, ✨feat

#33 ✨Feat: 로그인/회원가입 api 연동 & 헤더 분기처리
  package.json
  pnpm-lock.yaml
  public/icons/default_profile30.svg
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/RestoreAuth.tsx
  src/lib/api/auth.ts
  src/lib/api/axios.ts
  src/lib/store/useAuthStore.ts
Labels: 🎨style, ✨feat

#34 Feat: 체험 추가 및 수정 페이지에 모달 컴포넌트 추가 및 입력값 변경 감지 기능 구현
  public/icons/icon_alert.svg
  public/icons/icon_gray_plus.svg
  src/app/experiences/add/page.tsx
  src/app/experiences/edit/page.tsx
  src/components/common/CancelModal.tsx
  src/components/myExperiencesAddEdit/BannerImageInput.tsx
  src/components/myExperiencesAddEdit/IntroImagesInput.tsx
Labels: 🎨style, 🗑️remove, ✨feat

#36 ✨Feat: 예약 현황 페이지 구현
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/profile/reservationStatus/page.tsx
Labels: 🎨style, ✨feat

#43 ✨feat: 후기작성 모달 기초 ui 구현
  src/app/profile/reservations/page.tsx
  src/components/reservationList/ReviewModal.tsx
Labels: 🎨style

#45 ✨feat: 별점 기능 및 작성한 글자 수 표시 기능 구현
  src/app/globals.css
  src/components/reservationList/RatingStar.tsx
  src/components/reservationList/ReviewModal.tsx
Labels: 🎨style, ✨feat

#46 ✨feat: 홈 메인 UI 1차 구현 및 페이지네이션 공통 컴포넌트 적용
  public/icons/icon_chevron_left.svg
  public/icons/icon_chevron_right.svg
  public/imgs/banner.jpg
  public/imgs/thumbnail2.jpg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Header.tsx
  src/components/common/Pagination.tsx
  src/components/landing/AllActivities.tsx
  src/components/landing/Banner.tsx
  src/components/landing/CategoryFilter.tsx
  src/components/landing/LandingCard.tsx
  src/components/landing/MostCommentedActivities.tsx
  src/components/landing/PriceSortDropdown.tsx
  src/components/landing/SearchBar.tsx
Labels: 🎨style, ✨feat

#52 ✨Feat: 체험 상세 페이지 예약하기 모달 구현
  src/app/activities/[id]/page.tsx
  src/components/activities/ReservationFlow/CalendarStep.tsx
  src/components/activities/ReservationFlow/DesktopCard.tsx
  src/components/activities/ReservationFlow/MobileModal.tsx
  src/components/activities/ReservationFlow/ModalTrigger.tsx
  src/components/activities/ReservationFlow/PersonStep.tsx
  src/components/activities/ReservationFlow/ReservationContent.tsx
  src/components/activities/ReservationFlow/TabletModal.tsx
  src/components/activities/ReservationFlow/TimeSelectionStep.tsx
  src/components/activities/ReservationFlow/types.ts
Labels: 🎨style, ♻️refactor, ✨feat

#56 ✨feat: 생성된 axios instance 에 인터셉터를 이용해 토큰 추가
  src/app/profile/reservations/@modal/(.)exit/page.tsx
  src/lib/api/axios.ts
Labels: ✨feat

#57 ✨Feat: 체험 상세 페이지 UI 구현
  src/app/activities/[id]/page.tsx
  src/app/activities/layout.tsx
  src/components/activities/ActivitesDropdown.tsx
  src/components/activities/PhotoSection.tsx
  src/components/activities/ReservationFlow/MobileModal.tsx
  src/components/activities/ReservationFlow/ModalTrigger.tsx
  src/components/activities/ReservationFlow/ReservationContent.tsx
  src/components/activities/ReservationFlow/TabletModal.tsx
  src/components/activities/ReservationFlow/types.ts
  src/components/activities/ReviewCard.tsx
Labels: 🎨style, ✨feat

#58 ✨Feat: 검색 결과 페이지 UI 구현
  src/app/globals.css
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/landing/AllActivities.tsx
  src/components/landing/CategoryFilter.tsx
  src/components/landing/LandingCard.tsx
  src/components/landing/MostCommentedActivities.tsx
  src/components/landing/SearchBar.tsx
  src/components/search/NoResult.tsx
Labels: 🎨style, ✨feat

#61 🐛fix: 빌드 오류 수정
  src/app/activities/[id]/page.tsx
  src/app/experiences/add/page.tsx
  src/app/profile/info/page.tsx
  src/app/profile/myExperiences/page.tsx
  src/app/profile/reservationStatus/page.tsx
  src/app/profile/reservations/@modal/(.)exit/page.tsx
  src/app/profile/reservations/@modal/(.)review/page.tsx
  src/app/profile/reservations/@modal/exit/page.tsx
  src/app/profile/reservations/page.tsx
  src/app/profile/reservations/review/page.tsx
  src/app/search/page.tsx
  src/components/activities/ReservationFlow/DesktopCard.tsx
  src/components/common/Dropdown/Item.tsx
  src/components/common/Dropdown/Trigger.tsx
  src/components/landing/PriceSortDropdown.tsx
  src/components/profile/ProfileMenu.tsx
  src/components/reservationList/Badge.tsx
  src/components/reservationList/ReviewModal.tsx
Labels: 🐛fix

#69 ✨Feat: 지도 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/app/activities/[id]/page.tsx
  src/app/activities/layout.tsx
  src/components/activities/MapView.tsx
  tsconfig.json
Labels: 🎨style, 🔧chore, ✨feat

#67 🐛fix: 예약 내역 페이지 및 모달 관련 UI 에러 수정 및 에러메세지 해결
  src/app/profile/reservations/@modal/(.)exit/page.tsx
  src/app/profile/reservations/@modal/(.)review/page.tsx
  src/app/profile/reservations/review/page.tsx
  src/components/reservationList/ReservationCard.tsx
  src/components/reservationList/ReviewModal.tsx
Labels: 🐛fix

#75 ✨Feat/ 상세페이지와 추가하기 수정하기 전용 캘린더
  src/components/common/Calendar.tsx
  src/components/myExperiencesAddEdit/ReserveTimesInput.tsx
Labels: 🎨style, ♻️refactor, ✨feat

#82 🐛Fix: 리프레시 토큰 기반 accessToken 재발급 로직 구현 (401 Error)
  src/lib/api/auth.ts
  src/lib/api/axios.ts
Labels: 🐛fix

#85 ♻️Refactor: API 도입 전 체험 상세 페이지 리팩토링
  public/icons/icon_chevron_left.svg
  src/app/(main)/activities/[id]/page.tsx
  src/app/(main)/activities/layout.tsx
  src/components/activities/ActivitesDropdown.tsx
  src/components/activities/Activities.types.ts
  src/components/activities/ClientActivitesPage.tsx
  src/components/activities/MapView.tsx
  src/components/activities/PhotoSection.tsx
  src/components/activities/ReservationFlow/CalendarStep.tsx
  src/components/activities/ReservationFlow/DesktopCard.tsx
  src/components/activities/ReservationFlow/MobileModal.tsx
  src/components/activities/ReservationFlow/ModalTrigger.tsx
  src/components/activities/ReservationFlow/PersonStep.tsx
  src/components/activities/ReservationFlow/ReservationContent.tsx
  src/components/activities/ReservationFlow/TabletModal.tsx
  src/components/activities/ReservationFlow/TimeSelectionStep.tsx
  src/components/activities/ReservationFlow/types.ts
  src/components/activities/ReviewSection.tsx
  src/components/activities/StarRatingDisplay.tsx
  src/utils/formatPrice.ts
  src/utils/reservation.ts
Labels: 🐛fix, 🎨style, 🗑️remove, ♻️refactor, ✨feat

#86 ✨Feat: 후기 작성 모달 및 예약 내역 API 연결
  public/imgs/earth.svg
  src/app/(main)/profile/reservations/@modal/(.)review/[reservationId]/page.tsx
  src/app/(main)/profile/reservations/page.tsx
  src/app/globals.css
  src/components/reservationList/Badge.tsx
  src/components/reservationList/ReservationCard.tsx
  src/components/reservationList/ReviewModal.tsx
  src/lib/api/profile/reservationList.ts
Labels: 🎨style, ✨feat

#88 ✨Feat: 체험 상세 페이지 API 연동
  src/app/(main)/activities/[id]/page.tsx
  src/components/activities/ActivitesDropdown.tsx
  src/components/activities/ClientActivitesPage.tsx
  src/components/activities/ReviewSection.tsx
  src/lib/api/activities.ts
Labels: 🐛fix, ♻️refactor, ✨feat

#93 ✨Feat: 캘린더 props 추가 및 타입 안전성 강화
  src/components/common/Calendar.tsx
Labels: ✨feat

#94 ✨Feat: 체험등록하기 페이지 기능추가 및 api 연결
  next.config.ts
  src/app/(main)/experiences/add/page.tsx
  src/app/(main)/experiences/edit/page.tsx
  src/components/common/Input.tsx
  src/components/myExperiencesAddEdit/AddressInput.tsx
  src/components/myExperiencesAddEdit/CategoryInput.tsx
  src/components/myExperiencesAddEdit/DescriptionInput.tsx
  src/components/myExperiencesAddEdit/IntroImagesInput.tsx
  src/components/myExperiencesAddEdit/PriceInput.tsx
  src/components/myExperiencesAddEdit/ReserveTimesInput.tsx
  src/components/myExperiencesAddEdit/TitleInput.tsx
  src/lib/api/axios.ts
  src/lib/api/experiences.ts
Labels: 🫧modify, 🗑️remove, ✨feat

#97 ✨Feat: 예약 현황 api 연결
  src/app/(main)/profile/info/page.tsx
  src/app/(main)/profile/layout.tsx
  src/app/(main)/profile/myActivitiesStatus/page.tsx
  src/app/(main)/profile/myExperiences/page.tsx
  src/app/(main)/profile/reservationStatus/page.tsx
  src/components/common/ReservationCalendar.tsx
  src/components/profile/ProfileMenu.tsx
  src/components/profile/ReservationModal.tsx
  src/lib/api/profile/myActivities.ts
  src/lib/api/profile/myActivitiesStatus.ts
Labels: 🐛fix, 🎨style, ✨feat

#103 ♻️Refactor: 로컬스토리지 => Zustand로 변경
  package.json
  pnpm-lock.yaml
  src/app/(auth)/login/page.tsx
  src/components/activities/ClientActivitesPage.tsx
  src/components/common/Header.tsx
  src/components/common/Notification/NotiList.tsx
  src/lib/api/auth.ts
  src/lib/api/axios.ts
  src/lib/api/profile/index.ts
  src/lib/api/profile/myActivities.ts
  src/store/useAuthStore.ts
  src/store/useAuthStore.types.ts
Labels: ♻️refactor

#104 🐛fix: 이미지 업로드 문제 해결
  src/app/(main)/profile/info/page.tsx
  src/components/profile/ProfileMenu.tsx
  src/lib/api/profile/index.ts
  src/lib/api/profile/myActivitiesStatus.ts
  src/store/useAuthStore.ts
  src/store/useAuthStore.types.ts
Labels: 🐛fix

#109 🔧Chore: eslint-plugin-react-hooks 누락으로 리뷰 도구 오류 발생 수정
  package.json
  pnpm-lock.yaml
Labels: 🔧chore

#114 ♻️Refactor: 체험 추가,수정 리팩토링 및 api 타입 분리
  src/app/(main)/experiences/add/page.tsx
  src/app/(main)/experiences/edit/[id]/page.tsx
  src/components/common/Input.tsx
  src/components/myExperiencesAddEdit/IntroImagesInput.tsx
  src/components/myExperiencesAddEdit/ReserveTimesInput.tsx
  src/lib/api/experiences.ts
  src/lib/api/experiences/experiences.types.ts
  src/lib/api/experiences/index.ts
Labels: ♻️refactor, 📁chore, ✨feat

#118 ✨Feat: 예약 취소하기 API 연결 및 후기작성 모달 쿼리스트링으로 데이터 가져오기, 예약 내역 무한 스크롤 구현
  src/app/(main)/profile/reservations/@modal/(.)confirm/[reservationId]/page.tsx
  src/app/(main)/profile/reservations/@modal/(.)review/[reservationId]/page.tsx
  src/app/(main)/profile/reservations/@modal/exit/page.tsx
  src/app/(main)/profile/reservations/page.tsx
  src/app/(main)/profile/reservations/review/page.tsx
  src/app/globals.css
  src/components/reservationList/ReservationCard.tsx
  src/components/reservationList/StatusBadge.tsx
  src/lib/api/profile/reservationList.ts
Labels: 🎨style, ✨feat

#124 ✨Feat: 토스트 추가
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/test/page.tsx
Labels: 🔧chore, ✨feat

#122 ♻️Refactor: 예약 하기 모달 리팩토링
  src/components/activities/Activities.types.ts
  src/components/activities/ReservationFlow/CalendarStep.tsx
  src/components/activities/ReservationFlow/DesktopCard.tsx
  src/components/activities/ReservationFlow/MobileModal.tsx
  src/components/activities/ReservationFlow/ModalTrigger.tsx
  src/components/activities/ReservationFlow/PersonStep.tsx
  src/components/activities/ReservationFlow/ReservationContent.tsx
  src/components/activities/ReservationFlow/TabletModal.tsx
  src/components/activities/ReservationFlow/TimeSelectionStep.tsx
  src/components/common/DraggableContainer.tsx
  src/hooks/useDraggableBottomSheet.ts
  src/utils/reservation.ts
Labels: 🎨style, 🗑️remove, ♻️refactor, ✨feat

#130 ♻️Refactor: 메인 페이지 redesign 반영 2차 리팩토링
  public/icons/404_kkot.svg
  public/icons/flower.svg
  public/icons/wazylogowhite.svg
  public/imgs/baanner.jpg
  public/imgs/banner.jpg
  src/app/(main)/page.tsx
  src/app/(main)/search/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/landing/AllActivities.tsx
  src/components/landing/Banner.tsx
  src/components/landing/LandingCard.tsx
  src/components/landing/MostCommentedActivities.tsx
  src/components/landing/SearchBar.tsx
  src/components/search/NoResult.tsx
Labels: 🐛fix, 🎨style, ♻️refactor

#125 ♻️ Refactor: 조드, 훅폼, 타입분리, 기타 에러 처리
  package.json
  pnpm-lock.yaml
  src/app/(main)/experiences/add/page.tsx
  src/app/(main)/experiences/edit/[id]/page.tsx
  src/components/myExperiencesAddEdit/AddressInput.tsx
  src/components/myExperiencesAddEdit/BannerImageInput.tsx
  src/components/myExperiencesAddEdit/CategoryInput.tsx
  src/components/myExperiencesAddEdit/DescriptionInput.tsx
  src/components/myExperiencesAddEdit/IntroImagesInput.tsx
  src/components/myExperiencesAddEdit/PriceInput.tsx
  src/components/myExperiencesAddEdit/ReserveTimesInput.tsx
  src/components/myExperiencesAddEdit/TitleInput.tsx
  src/components/myExperiencesAddEdit/types.ts
  src/lib/schema/experiencesSchema.ts
Labels: ♻️refactor, ✨feat

#116 ♻️Refactor: profile page 1차 리펙토링
  public/imgs/loading.png
  public/imgs/profile_default.png
  src/app/(main)/profile/info/page.tsx
  src/app/(main)/profile/layout.tsx
  src/app/(main)/profile/myActivitiesStatus/page.tsx
  src/app/(main)/profile/myExperiences/page.tsx
  src/app/(main)/profile/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/components/profile/ExperienceCard.tsx
  src/components/profile/ProfileMenu.tsx
  src/components/profile/ReservationModal.tsx
  src/components/profile/common/ErrorMessage.tsx
  src/components/profile/common/LoadingSpinner.tsx
  src/components/profile/common/MobilePageHeader.tsx
  src/components/profile/common/components.ts
  src/components/profile/reservationStatus/ReservationModal.tsx
  src/hooks/profile/hooks.ts
  src/hooks/profile/useCalendarData.ts
  src/hooks/profile/useReservationDashboard.ts
  src/hooks/profile/useReservationModal.ts
Labels: 🐛fix, 🎨style, ♻️refactor, ✨feat

#137 🐛Fix: 헤더 스타일 변경으로 인해 sticky가 제대로 동작하지 않던 문제 수정
  src/components/activities/ClientActivitiesPage.tsx
Labels: 🐛fix, 🎨style

#138 ♻️Refactor: 후기작성 모달 react-hook-form + zod 적용
  src/app/(main)/profile/reservations/@modal/(.)review/[reservationId]/page.tsx
  src/components/reservationList/ReviewModal.tsx
  src/lib/api/profile/reservationList.ts
  src/lib/schema/reservationsSchema.ts
Labels: ♻️refactor
