Repository sprint15-part4-team5/wazy, pull requests merged in 2025-08, with the labels that each got.

#148 ♻️Refactor: 홈 화면 UI 및 알림 기능 전반 리팩토링 3차
  public/icons/default_profile30.svg
  public/icons/icon_X.svg
  public/icons/icon_facebook.svg
  public/icons/icon_github.png
  public/icons/icon_google.svg
  public/icons/icon_instagram.svg
  public/icons/icon_youtube.svg
  public/icons/logoHorizon.svg
  public/icons/logoVertical.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/search/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/LoadingPage.tsx
  src/components/common/Notification/NotiBell.tsx
  src/components/common/Notification/NotiList.tsx
  src/components/landing/AllActivities.tsx
  src/components/landing/Banner.tsx
  src/components/landing/LandingCard.tsx
  src/components/landing/MostCommentedActivities.tsx
  src/components/landing/PriceSortDropdown.tsx
  src/components/landing/SearchBar.tsx
  src/hooks/useAutoScroll.ts
Labels: 🐛fix, 🗑️remove, ♻️refactor, ✨feat

#153 ♻️Refactor: 체험 상세 페이지 UI/UX 개선
  src/components/activities/MapView.tsx
  src/components/activities/ReservationFlow/CalendarStep.tsx
  src/components/activities/ReservationFlow/DesktopCard.tsx
  src/components/activities/ReservationFlow/MobileModal.tsx
  src/components/activities/ReservationFlow/ModalTrigger.tsx
  src/components/activities/ReservationFlow/ReservationContent.tsx
  src/components/activities/ReservationFlow/TabletModal.tsx
  src/components/activities/ReservationFlow/TimeSelectionStep.tsx
  src/components/activities/sections/ActivityPhotoSection.tsx
  src/components/activities/sections/ActivityReviewSection.tsx
  src/components/common/Calendar.tsx
Labels: 🐛fix, 🎨style, ♻️refactor

#158 ✨Feat: 렌딩페이지 섹션4 구현
  src/components/activities/ReviewCard.tsx
  src/components/landing/Section4.tsx
  src/utils/cn.ts
Labels: 🎨style, ✨feat

#160 ✨Feat: 랜딩페이지 섹션1 구현
  src/app/(main)/page.tsx
  src/components/landing/Section1.tsx
Labels: 🎨style, ✨feat

#155 ♻️ refatory : 2차 리팩토링, 유효성검사, price인풋 숫자 해결, 모달배경 막음, 모달 ux개선
  public/icons/icon_alert_cancel.svg
  src/app/(main)/experiences/add/page.tsx
  src/app/(main)/experiences/edit/[id]/page.tsx
  src/components/common/CancelModal.tsx
  src/components/common/Input.tsx
  src/components/common/LoadingPage.tsx
  src/components/common/TimeDropdown.tsx
  src/components/myExperiencesAddEdit/AddressInput.tsx
  src/components/myExperiencesAddEdit/BannerImageInput.tsx
  src/components/myExperiencesAddEdit/CategoryInput.tsx
  src/components/myExperiencesAddEdit/DescriptionInput.tsx
  src/components/myExperiencesAddEdit/IntroImagesInput.tsx
  src/components/myExperiencesAddEdit/MyExperiences.ts
  src/components/myExperiencesAddEdit/PriceInput.tsx
  src/components/myExperiencesAddEdit/ReserveTimesInput.tsx
  src/components/myExperiencesAddEdit/TitleInput.tsx
  src/lib/api/experiences/experiences.types.ts
Labels: 🐛fix, ♻️refactor

#164 Feat: 렌딩페이지 구현
  src/app/(main)/page.tsx
  src/components/common/Header.tsx
  src/components/landing/.gitkeep
Labels: 🐛fix, ✨feat

#172 ✨Feat: 랜딩페이지 세션3 ui 수정
  src/components/common/TimeDropdown.tsx
  src/components/landing/Section3.tsx
Labels: ♻️refactor, ✨feat

#168 🎨Style: 랜딩페이지 섹션2 수정
  src/components/landing/section2.tsx
Labels: 🎨style

#173 ✨Feat: 라이트 박스 구현
  src/components/activities/LightBox.tsx
  src/components/activities/sections/ActivityPhotoSection.tsx
Labels: 🐛fix, ✨feat

#183 ♻️Refactor: 예약 내역 페이지 및 후기작성 모달 QA 반영
  src/app/(main)/profile/reservations/@modal/(.)confirm/[reservationId]/page.tsx
  src/app/(main)/profile/reservations/@modal/(.)exit/page.tsx
  src/app/(main)/profile/reservations/page.tsx
  src/components/reservationList/ReservationCard.tsx
  src/components/reservationList/ReviewModal.tsx
Labels: 🎨style, ♻️refactor, ✨feat

#188 ♻️Refactor: QA 사항 수정
  src/components/auth/Input.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Notification/NotiBell.tsx
  src/components/common/Notification/NotiList.tsx
  src/lib/schema/authSchema.ts
Labels: ♻️refactor

#184 ✨Feat: 스켈레톤 UI 구현 및 적용
  src/components/activities/ClientActivitiesPage.tsx
  src/components/activities/ResponsiveActivityPageSkeleton.tsx
Labels: 🎨style, ✨feat

#186 Refactor: 섹션 4 패딩 값 수정
  src/components/landing/Section4.tsx
Labels: 🎨style, ♻️refactor

#189 ✨Feat: Router Guard 구현
  src/app/(main)/experiences/layout.tsx
  src/app/(main)/profile/layout.tsx
  src/components/auth/RouterGuard.tsx
Labels: ✨feat
